[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "probe-rs run --chip RP2040"
runner = " ~/.pico-sdk/openocd/0.12.0+dev/openocd -s ~/.pico-sdk/openocd/0.12.0+dev/scripts -f interface/cmsis-dap.cfg -f target/rp2350.cfg -c 'adapter speed 5000' -c 'program embassy_rp_2_template verify reset exit"
#'

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"
